### ISSUE TITLE
Chrome Extention no longer available

### ISSUE THREAD

**Issue by SonOfDiablo** [plibither8/asciinema-player-for-github#2]
As the title hints at, the Chrome Extension is no longer available on the Chrome Web Store.

Would it be possible to get it back on there?

**Comment by plibither8** [comment]
Hi, thanks for creating this issue. The extension was taken down from CWS because of not a very skewed and not clear:

> We routinely review items in the Chrome Web Store for compliance with our Program policies to ensure a safe and trusted experience for our users. Your item, "asciinema Player For GitHub," with ID: mkllmpcfhjcbkmegdpnaemhpdddffhil, does not work or provide any functionality upon installation. Items on the Chrome Web Store should work and provide the promised functionality that aligns with the description of the item.

I did write them an email regarding the issue, and requested in detail what _exactly_ they wanted to change, but I did not receive any response. In turn, the extension was removed.

I have not got the time to put up again, but I assure you I will work on it soon.
Thanks again, and cheers!

**Comment by SonOfDiablo** [comment]
Oh I see, that seems pretty shitty on Google's part :/

Would it be possible to provide the crx as a release here on Github such that we can install it without having to build it ourselves?

**Comment by plibither8** [comment]
Damn, this is a _super_ late reply, sorry for that.

Nevertheless, I've created a release for the CRX file, you can find it here: https://github.com/plibither8/asciinema-player-for-github/releases/tag/19.7.1.1721

Cheers!
